"""Constants"""
RS_METHOD_EVENT: str = "rs_method_call"
RS_METHOD_MESSAGE: str = "rs_method_message"
RS_MESSAGE_CALL_ATTEMPT: str = "attempt"
RS_MESSAGE_CALL_SUCCESS: str = "success"
RS_MESSAGE_CALL_FAILED: str = "failed"
